### PR TITLE
Use the local dockerfile over the image

### PR DESCRIPTION
**Pull request by escopecz**

### CODE REVIEW

**Comment by dennisameling** [comment]
@escopecz sorry about that `dennisameling/python-vale:latest` image - didn't know it was still lingering around! It was basically built from [this](https://github.com/dennisameling/sphinx-vale-docker/blob/main/Dockerfile) Dockerfile and then I pushed it to Docker Hub [here](https://registry.hub.docker.com/r/dennisameling/python-vale/tags), so Gitpod could access it.

Were you able to get things to work already? Happy to chime in if you're still running into issues! CC @RCheesley

**Comment by RCheesley** [comment]
@dennisameling we have been trying to get it working but it seems there's a bug with the Esbonio language server currently which is preventing it from running: https://github.com/swyddfa/esbonio/issues/896#issuecomment-2373231575. It seems to install fine, but never starts up.

Any help you might be able to give would be awesome!

**Comment by dennisameling** [comment]
Had to read up a bit on the current situation. Looks like the [reStructuredText extension](https://open-vsx.org/extension/lextudio/restructuredtext) that we used has [removed support for previews](https://github.com/vscode-restructuredtext/vscode-restructuredtext/releases/tag/190.1.17) in version 190.1.17, back in January of this year. Apparently folks should now be using the new [Esbonio VS Code extension](https://open-vsx.org/extension/swyddfa/esbonio), which is still a pre-release version, and seems to be lacking proper documentation.

When I download the older `.vsix` for [190.1.4](https://open-vsx.org/extension/lextudio/restructuredtext/190.1.4) and drag it into GitPod, then use the "Install from VSIX" option, the preview is working just fine:

afbeelding

afbeelding

So until Esbonio releases their v1 stable version, you may want to replace this snippet in `.gitpod.yml`:

```yaml
vscode:
  extensions:
    - ms-python.python
    - lextudio.restructuredtext
```
... with this:

```yaml
vscode:
  extensions:
    - ms-python.python
    - lextudio.restructuredtext@190.1.4
```

That would give a bit more breathing space to figure out the Esbonio extension setup. Hope this helps! 🙏🏼

**Comment by escopecz** [comment]
@dennisameling Thanks for looking into it! Much appreciated! 

I'm getting this message now but from the language server output it seems like it's done:
Screenshot 2024-10-11 at 10 13 37

Also, do you have some idea how to avoid the failing CI with rate-limited link?:
```
-rate limited-   https://github.com/search?q=repo%3Amautic%2Fmautic+Dashboard+menu+language%3AINI | sleeping...
-rate limited-   https://github.com/search?q=repo%3Amautic%2Fmautic+Dashboard+menu+language%3AINI | sleeping...
-rate limited-   https://github.com/search?q=repo%3Amautic%2Fmautic+Dashboard+menu+language%3AINI | sleeping...
-rate limited-   https://github.com/search?q=repo%3Amautic%2Fmautic+Dashboard+menu+language%3AINI | sleeping...
-rate limited-   https://github.com/search?q=repo%3Amautic%2Fmautic+Dashboard+menu+language%3AINI | sleeping...
```

**Comment by dennisameling** [comment]
> I'm getting this message now but from the language server output it seems like it's done:

Can you click "esbonio" in the bottom right corner of the screen? That'll trigger a rebuild. I just started a fresh GitPod instance based on your latest commit here, and it's working nicely 👌🏼 

> Also, do you have some idea how to avoid the failing CI with rate-limited link?:

IIRC GitHub made a change a couple months ago to to prevent unauthenticated users from using the search page. If you open an incognito window on your local machine and go to the URL in question (https://github.com/search?q=repo%3Amautic%2Fmautic+Dashboard+menu+language%3AINI), you'll get the rate limit as well. Apparently there's an option in `linkcheck` to [provide auth](https://www.sphinx-doc.org/en/master/usage/configuration.html#confval-linkcheck_auth), so we might be able to leverage GitHub's `GITHUB_TOKEN` that it exposes in the CI pipeline. Will check. If that's too much work to implement, we might as well just [ignore](https://www.sphinx-doc.org/en/master/usage/configuration.html#confval-linkcheck_ignore) this URL from `linkcheck`.

**Comment by dennisameling** [comment]
> If that's too much work to implement, we might as well just [ignore](https://www.sphinx-doc.org/en/master/usage/configuration.html#confval-linkcheck_ignore) this URL from linkcheck.

I went with that route after some checks. There's no easy way to generate a session cookie for the GitHub UI for this purpose, so let's ignore it.

@escopecz can you add [this commit](https://github.com/dennisameling/user-documentation/commit/d07450f7612851306c945bc4644e0880493a6478) to your PR here? That should fix the build. The broken 404 links should be replaced sometime.

**Comment by escopecz** [comment]
@dennisameling thank you! The CI is green now. I'm not sure what I do wrong or where to search for an error message:
Screenshot 2024-10-11 at 13 47 26
Is gitpod somehow remembering extensions from my previous sessions?

**Review by RCheesley — APPROVED** [review]
It's working OK for me - I can now preview the files without a problem and Esbonio is loading! Thanks so much @dennisameling and @escopecz for looking into this issue!

**Comment by escopecz** [comment]
Let's get this merged if it works for the 2 of you :)

**Pull request merged**
