### PR TITLE
Add forms section

### LINKED ISSUE #46: Add the Forms section
- [ ] Managing forms
- [ ] Progressive profiling
- [ ] Recording UTM tags
- [ ] Conditional fields

I think these will all be in one page, using heading to navigate the sections.

### PR DESCRIPTION
**Pull request by RCheesley**
This PR resolves #46.

Now ready for review 🎉 

Sections included:

- [x] Form types
- [x] General options
- [x] Form fields
- [x] Field editor
- [x] Form actions
- [x] Adding forms to pages 
- [x] Blocking domains

<a href="https://gitpod.io/#https://github.com/mautic/user-documentation/pull/68"></a>

### CODE REVIEW

**Comment by RCheesley** [comment]
The build is failing on this as the /download page on the main Mautic site seems to be throwing a 404.

Just waiting on that to get sorted but otherwise this is good to be reviewed.

**Comment by fakela** [comment]
@RCheesley you might want to update and merge changes as well

**Comment by RCheesley** [comment]
Done - should not impact this PR though as it's other pages being changed :)

**Comment by fakela** [comment]
> Done - should not impact this PR though as it's other pages being changed :)

Oh my😦 There is now Vale error,  but overall the PR looks good! 

If that is fixed, the PR can be merged :)

**Comment by RCheesley** [comment]
That's the Vale gods placated, and the build error is just the broken links!

**Pull request merged**
