### PR TITLE
Add Exclude processed entities to docs

### PR DESCRIPTION
**Pull request by favour-chibueze**
Allow to exclude campaigns and segments from processing. #13383

### CODE REVIEW

**Comment by RCheesley** [comment]
Please remove the focus items file from this PR :)

**Comment by RCheesley** [comment]
@favour-chibueze we need to remove all the previous commits from this PR - maybe start again but from the 5.x branch rather than with the previous work applied?

**Comment by favour-chibueze** [comment]
> @favour-chibueze we need to remove all the previous commits from this PR - maybe start again but from the 5.x branch rather than with the previous work applied?

Alright

**Comment by RCheesley** [comment]
@favour-chibueze this one still needs some attention, I think.

**Comment by RCheesley** [comment]
Maybe #291 supersedes this one?

**Pull request closed without merging**
