### PR TITLE
 Installation with DDEV

### PR DESCRIPTION
**Pull request by pragatijain**
Updated Installing with GitHub to Installing with DDEV.

### CODE REVIEW

**Comment by pragatijain** [comment]
Using [this](https://kb.mautic.org/knowledgebase/development/how-to-install-mautic-using-ddev#further-useful-ddev-tips-and-tricks) Mautic KB article, I reviewed the original page for relevance and accuracy.

**Comment by fakela** [comment]
@pragatijain I will go through this accordingly. Thank you for the PR.

**Comment by fakela** [comment]
Looks good to me 👍

**Comment by RCheesley** [comment]
Hey folks, this is actually quite an outdated article. The most updated is probably here: https://contribute.mautic.org/contributing-to-mautic/tester#setting-up-a-local-testing-environment 

Maybe we can update it (perhaps make a new issue)?

**Pull request merged**
